### ISSUE TITLE
Adding transitions to parent state and sending triggers causes NeglectedTriggerException

### ISSUE THREAD

**Issue by cs-manughian** [johans2/FSM#1]
I'm building a HSFM for my character state, which includes substates such as walk and jump:

```
    void Start()
    {
        characterState = new CharacterState();
        walkState = new WalkState(characterRigidBody);
        jumpState = new JumpState(characterRigidBody);

        // Create a hierarchy by adding substates and transitions
        characterState.LoadSubState(walkState);
        characterState.LoadSubState(jumpState);

        characterState.AddTransition(walkState, jumpState, Triggers.JUMP);
        characterState.AddTransition(jumpState, walkState, Triggers.WALK);

        // Start the state machine
        characterState.EnterStateMachine();
    }
```

In my update function, I invoke `SendTrigger` to change the state, but I get a `NeglectedTriggerException` despite having added the transitions to the parent state on start. It looks like the transition is being added to the substate and not the parent state in the `AddTransition` function, so I suspect this may be the issue. 

```
    void Update()
    {
        characterState.UpdateStateMachine();
        if (Input.GetButton("Jump"))
        {
            characterState.SendTrigger(Triggers.JUMP);
        }
    }
```

**Comment by johans2** [comment]
Hi! 
Thats strange.. the setup looks correct and this exact case should be covered by the test called `TransitionSimple()` in HFMSTests.cs.

However, it looks like you are using `Input.GetButton("Jump")` instead of `Input.GetButtonDown("Jump")` in your update method. This means that you will send the trigger every frame the button is held down (even when you have already transitioned to `JumpState`). `JumpState` has no transition on that trigger, which would then raise the exception. Could you test and see if this is the issue?

/Johan
